### ISSUE TITLE
Add GPT4 API

### ISSUE THREAD

**Issue by tim-gromeyer** [curcic/GUI-GPT#1]
Hello,
I recently got access to the GPT4 API and I was searching for a gui.
I came across this project but there is no ChatGPT/GPT4 option.

Will this be added? If not, feel free to close the issue

**Comment by curcic** [comment]
> Hello, I recently got access to the GPT4 API and I was searching for a gui. I came across this project but there is no ChatGPT/GPT4 option.
> 
> Will this be added? If not, feel free to close the issue

Yes, GPT4 is a planned priority option and will be added.

I'm in the process of gaining access to the API so that I can test the code before publishing it.

**Comment by tim-gromeyer** [comment]
Cool, thank you!

**Comment by curcic** [comment]
GPT-4 API has been added.
